# Generated by Django 5.1.1 on 2024-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('fee', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
